# Generated by Django 5.2.6 on 2025-09-30 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('artista', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.URLField(help_text='URL de la carátula del álbum')),
                ('spotify_link', models.URLField(help_text='Link al álbum en Spotify')),
            ],
        ),
    ]
