# Generated by Django 5.2.6 on 2025-09-20 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('asunto', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PEN', 'Pendiente'), ('PRO', 'En Proceso'), ('RES', 'Resuelto')], default='PEN', max_length=3)),
                ('notas_internas', models.TextField(blank=True, null=True)),
                ('origen', models.CharField(default='web', max_length=50)),
            ],
        ),
    ]
